version: '3.9'

services:
  client:
    platform: linux/amd64
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
